name: Gomod2nix

on:
  push:
    paths:
      - "go.mod"
      - "go.sum"

jobs:
  update-gomod2nix_toml:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - uses: cachix/install-nix-action@v31
    - name: Update gomod2nix.toml
      run: nix run github:nix-community/gomod2nix/v1.7.0 --override-input nixpkgs nixpkgs
    - name: Commit and push gomod2nix.toml update
      run: |
        set -euo pipefail

        if ! git diff --quiet; then
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          git add gomod2nix.toml
          git commit -m "nix: update gomod2nix.toml"

          for attempt in 1 2 3; do
            if git push; then
              echo "Successfully pushed gomod2nix.toml update"
              exit 0
            fi
            echo "Push attempt $attempt failed, pulling and retrying..."
            git pull --rebase
            sleep $((attempt*2))
          done

          echo "Failed to push after retries" >&2
          exit 1
        fi
